// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectFileTools
{
    static class Vsix
    {
        public const string Id = "e22f3d7e-6b01-4ef8-b3cb-ea293a87b00e";
        public const string Name = "Project File Tools";
        public const string Description = @"Provides Intellisense and other tooling for XML based project files such as .csproj and .vbproj files.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Mike Lorbetske";
        public const string Tags = "project, csproj, vbproj";
    }
}
